In [196]:
import pysftp  # Leon, ich nutze pysftp 0.2.8
import sys
import os
import pandas as pd

# Leon: 
print(pd.__version__)  # Code funktioniert mit der Version noch, trotz Warnmeldung unten (new Copy-on-Write-System)

2.2.3

In [197]:
#download files again (yes/no)?
download = "yes"

#set year for data creation
year = '2024'

In [198]:
#ENTSO-E sftp settings
host = "sftp-transparency.entsoe.eu"
password = "3?mJ}V4us?!L}5E"                
username = "jsavelsberg@ethz.ch"                
port = '22'

In [199]:
dir_out = "../parsed_data/"

In [200]:
map_country = {   ### Leon, Fehlende Länder, neue Codes (diverse NaN)
'AT' : 'AT', ##
'RS' : 'RS',  ## 
'SK' : 'SK',  ## 
'HU' : 'HU',  ## 
'RO' : 'RO',  ## 
'ES' : 'ES',  ## 
'FR' : 'FR',  ## 
'DE_LU' : 'DE',  ## NEW, DE ###
'IT-CNORTH' : 'IT',  ## NEW, ITAL ### 
'IT-CSOUTH' : 'IT',
'IT-Calabria' : 'IT',
'SI' : 'SI',  ## 
'NL' : 'NL',  ## 
'BE' : 'BE', ##
'NO5' : 'NO',#****
'NO3' : 'NO',#****
'SE2' : 'SE',#++++
'LV' : 'LV',  ## 
'NO4' : 'NO',#****
'SE4' : 'SE',#++++
'GB' : 'GB',  ############ ??????? GB kommt im Heruntergeladenen nicht vor, kann also auch nicht gemappt werden (Brexit) 
'PT' : 'PT', ## 
'GR' : 'GR',  ## 
'IT-NORTH' : 'IT',
'IT-SACOAC' : 'IT',
'EE' : 'EE',  ## 
'NO2' : 'NO',#****
'SE1' : 'SE',#++++
'NO1' : 'NO',#****
'DK2' : 'DK',  ## 
'FI' : 'FI',  ## 
'DK1' : 'DK',  ## 
'LT' : 'LT',  ## 
'IT-SACODC' : 'IT',
'IT-SOUTH' : 'IT',
'IT-Sardinia' : 'IT',
'IT-Sicily' : 'IT',
'SE3' : 'SE', #++++
'PL' : 'PL',  ## 
'BG' : 'BG',  ## 
'HR' : 'HR',  ## 
'CH' : 'CH',  ## 
'CZ' : 'CZ',  ## 
'IE_SEM' : 'IE',  ## 
'ME' : 'ME',  #Added: 
'MK' : 'MK', 
'NO2NSL' : 'NO', 
'UA_IPS' : 'UA'
    
 }

In [201]:
bz_countries = {'IT','SE','DK','NO'}

In [202]:
#Connect to ENTSO-E Transparency FTP
#for this to work, pysftp 0.2.8 is needed!
path = '/TP_export/'
path_local = os.path.join(os.pardir,'source_data/ENTSOE/')

In [203]:
if download =="yes":
    with pysftp.Connection(host=host, username=username, password=password) as sftp:
        print("Connection succesfully established.")
        
        # show list of files
        files = sftp.listdir('/TP_export/')
        print(files)

Connection succesfully established.
['AcceptedAggregatedOffers_17.1.D', 'ActivatedBalancingEnergy_17.1.E', 'ActualCapacitiesAndOutlookOnFrequencyRestorationReserveAndReplacementReserve_SOGL_188.3_188.4_189.2_189.3_r3', 'ActualGenerationOutputPerGenerationUnit_16.1.A_r2.1', 'ActualTotalLoad_6.1.A', 'AggregatedBalancingEnergyBids_12.3.E_r3', 'AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D', 'AggregatedGenerationPerType_16.1.B_C', 'AmountAndPricesPaidOfBalancingReservesUnderContract_17.1.B_C_r2', 'AmountOfBalancingReservesUnderContract_17.1.B', 'BalancingBorderCapacityLimitations_IFs_4.3_4.4_r2', 'ChangesInActualAvailabilityOfConsumptionUnits_7.1.B', 'ChangesInActualAvailabilityOfOffshoreGridInfrastructureReasons_10.1.C', 'ChangesInActualAvailabilityOfOffshoreGridInfrastructure_10.1.C', 'ChangesToBidAvailability_IFs_mFRR9.9_aFRR9.6_9.8_r3', 'CommercialSchedulesNetPositions_12.1.F_r3', 'CommercialSchedules_12.1.F_r3', 'CostsOfCongestionManagement_13.1.C', 'Countertrading_13.1.B_r2.1', 'CrossBorderBalancingEnergyActivated_17.1.J', 'CrossBorderBalancingPrices_17.1.J', 'CrossBorderBalancingVolumesOfExchangedBidsAndOffers_17.1.J', 'CrossBorderCapacityForDcLinksIntraday_11.3', 'CrossBorderMarginalPriceForAutomaticFrequencyRestorationReserveStandardProduct_IF_aFRR3.16_r3', 'CrossZonalBalancingCapacity_12.3.H_12.3.I_r3', 'CurrentBalancingState_12.3.A_r3', 'CurrentGenerationForecastForWindAndSolar_14.1.D', 'DayAheadAggregatedGeneration_14.1.C', 'DayAheadFlowBasedAllocations_11.1', 'DayAheadGenerationForecastForWindAndSolar_14.1.D', 'DayAheadTotalLoadForecast_6.1.B', 'ElasticDemands_IFs_mFRR3.4_aFRR3.4_r3', 'EnergyPrices_12.1.D_r3', 'ExchangedReserveCapacity_SOGL_190.3_r3', 'ExpansionAndDismantlingProjects_9.1', 'ExplicitAllocationsAuctionRevenueDaily_12.3.A', 'ExplicitAllocationsAuctionRevenueIntraday_12.3.A', 'ExplicitAllocationsAuctionRevenueMonthly_12.3.A', 'ExplicitAllocationsAuctionRevenueOther_12.3.A', 'ExplicitAllocationsAuctionRevenueWeekly_12.3.A', 'ExplicitAllocationsAuctionRevenueYearly_12.3.A', 'ExplicitAllocationsUseOfTransferCapacityDaily_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityIntraday_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityMonthly_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityOther_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityWeekly_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityYearly_12.1.A', 'Export_log.csv', 'Export_log_r3.csv', 'Export_oce_log_r3.csv', 'Fallbacks_IF_IN7.2_mFRR3.11_aFRR3.10_r3', 'FcrTotalCapacity_187.2', 'FinancialExpensesAndIncomeForBalancing_17.1.I', 'FinancialExpensesAndIncomeForBalancing_17.1.I_r3', 'FlowBasedAllocationsCongestionIncomeDaily_12.1.E', 'FlowBasedAllocationsCongestionIncome_12.1.E_r3', 'ForecastedDayAheadTransferCapacities_11.1', 'ForecastedMonthAheadTransferCapacities_11.1', 'ForecastedWeekAheadTransferCapacities_11.1', 'ForecastedYearAheadTransferCapacities_11.1', 'FrequencyContainmentReserveAmountAndShares_SOGL_187.2_r3', 'FrrActualCapacity_188.4', 'ImbalancePrices_17.1.G_r2.1', 'ImplicitAllocationsCongestionIncome_12.1.E_r3', 'ImplicitAllocationsNetPositions_12.1.E_r3', 'InstalledCapacityProductionUnit_14.1.B', 'InstalledGenerationCapacityAggregated_14.1.A', 'IntradayGenerationForecastForWindAndSolar_14.1.D', 'MonthAheadTotalLoadForecast_6.1.D', 'NettedAndExchangedVolumesPerBorder_IFs_IN3.10_mFRR3.17_r3', 'NettedAndExchangedVolumes_IFs_IN3.10_mFRR3.17_r3', 'OfferedDayAheadTransferCapacityImplicit_11.1', 'OfferedDayAheadTransferCapacity_11.1', 'OfferedIntradayTransferCapacityImplicit_11.1', 'OfferedIntradayTransferCapacity_11.1', 'OfferedMonthAheadTransferCapacity_11.1', 'OfferedOtherTransferCapacity_11.1', 'OfferedTransferCapacitiesContinuous_11.1_r3', 'OfferedTransferCapacitiesExplicit_11.1_r3', 'OfferedTransferCapacitiesImplicit_11.1_r3', 'OfferedWeekAheadTransferCapacity_11.1', 'OfferedYearAheadTransferCapacity_11.1', 'OtherMarketInformation_r3', 'PermanentAllocationLimitations_IFs_4.5_r3', 'PhysicalFlows_12.1.G', 'PlannedUnavailabilityOfConsumptionUnits_7.1.A', 'PricesOfActivatedBalancingEnergy_17.1.F_r3', 'PricesOfProcuredBalancingReserves_17.1.C', 'ProcuredBalancingCapacity_12.3.F', 'ProcuredBalancingCapacity_12.3.F_r3', 'ProductionAndGenerationUnits_r2', 'RedispatchingCrossBorder_13.1.A_r2.1', 'RedispatchingInternal_13.1.A_r2.1', 'Redispatching_13.1.A', 'ResultsOfTheCriteriaApplicationProcess_SOGL_185.4_r3', 'RrActualCapacity_189.3', 'SharesOfFcrCapacity_187.2', 'TotalCapacityAlreadyAllocated_12.1.C_r3', 'TotalCapacityNominated_12.1.B', 'TotalImbalanceVolumes_17.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesDailyImplicit_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesDaily_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesIntraday_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesMonthly_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesYearly_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountries_12.1.H_r3', 'UnavailabilityInTransmissionGridReasons_10.1.A_B', 'UnavailabilityInTransmissionGrid_10.1.A_B', 'UnavailabilityOfGenerationUnitsReasons_15.1.A_B', 'UnavailabilityOfGenerationUnits_15.1.A_B', 'UnavailabilityOfProductionUnitsReasons_15.1.C_D', 'UnavailabilityOfProductionUnits_15.1.C_D', 'UseOfAllocatedCrossZonalBalancingCapacity_12.3.H_12.3.I_r2', 'WeekAheadTotalLoadForecast_6.1.C', 'YearAheadForecastMargin_8.1', 'YearAheadTotalLoadForecast_6.1.E', 'zip']

In [204]:
# Leon: 
with pysftp.Connection(host=host, username=username, password=password) as sftp:
    print("Inhalt von /TP_export/EnergyPrices_12.1.D_r3/:")
    print(sftp.listdir('/TP_export/EnergyPrices_12.1.D_r3/'))

Inhalt von /TP_export/EnergyPrices_12.1.D_r3/:
['2014_01_EnergyPrices_12.1.D_r3.csv', '2014_12_EnergyPrices_12.1.D_r3.csv', '2015_01_EnergyPrices_12.1.D_r3.csv', '2015_02_EnergyPrices_12.1.D_r3.csv', '2015_03_EnergyPrices_12.1.D_r3.csv', '2015_04_EnergyPrices_12.1.D_r3.csv', '2015_05_EnergyPrices_12.1.D_r3.csv', '2015_06_EnergyPrices_12.1.D_r3.csv', '2015_07_EnergyPrices_12.1.D_r3.csv', '2015_08_EnergyPrices_12.1.D_r3.csv', '2015_09_EnergyPrices_12.1.D_r3.csv', '2015_10_EnergyPrices_12.1.D_r3.csv', '2015_11_EnergyPrices_12.1.D_r3.csv', '2015_12_EnergyPrices_12.1.D_r3.csv', '2016_01_EnergyPrices_12.1.D_r3.csv', '2016_02_EnergyPrices_12.1.D_r3.csv', '2016_03_EnergyPrices_12.1.D_r3.csv', '2016_04_EnergyPrices_12.1.D_r3.csv', '2016_05_EnergyPrices_12.1.D_r3.csv', '2016_06_EnergyPrices_12.1.D_r3.csv', '2016_07_EnergyPrices_12.1.D_r3.csv', '2016_08_EnergyPrices_12.1.D_r3.csv', '2016_09_EnergyPrices_12.1.D_r3.csv', '2016_10_EnergyPrices_12.1.D_r3.csv', '2016_11_EnergyPrices_12.1.D_r3.csv', '2016_12_EnergyPrices_12.1.D_r3.csv', '2017_01_EnergyPrices_12.1.D_r3.csv', '2017_02_EnergyPrices_12.1.D_r3.csv', '2017_03_EnergyPrices_12.1.D_r3.csv', '2017_04_EnergyPrices_12.1.D_r3.csv', '2017_05_EnergyPrices_12.1.D_r3.csv', '2017_06_EnergyPrices_12.1.D_r3.csv', '2017_07_EnergyPrices_12.1.D_r3.csv', '2017_08_EnergyPrices_12.1.D_r3.csv', '2017_09_EnergyPrices_12.1.D_r3.csv', '2017_10_EnergyPrices_12.1.D_r3.csv', '2017_11_EnergyPrices_12.1.D_r3.csv', '2017_12_EnergyPrices_12.1.D_r3.csv', '2018_01_EnergyPrices_12.1.D_r3.csv', '2018_02_EnergyPrices_12.1.D_r3.csv', '2018_03_EnergyPrices_12.1.D_r3.csv', '2018_04_EnergyPrices_12.1.D_r3.csv', '2018_05_EnergyPrices_12.1.D_r3.csv', '2018_06_EnergyPrices_12.1.D_r3.csv', '2018_07_EnergyPrices_12.1.D_r3.csv', '2018_08_EnergyPrices_12.1.D_r3.csv', '2018_09_EnergyPrices_12.1.D_r3.csv', '2018_10_EnergyPrices_12.1.D_r3.csv', '2018_11_EnergyPrices_12.1.D_r3.csv', '2018_12_EnergyPrices_12.1.D_r3.csv', '2019_01_EnergyPrices_12.1.D_r3.csv', '2019_02_EnergyPrices_12.1.D_r3.csv', '2019_03_EnergyPrices_12.1.D_r3.csv', '2019_04_EnergyPrices_12.1.D_r3.csv', '2019_05_EnergyPrices_12.1.D_r3.csv', '2019_06_EnergyPrices_12.1.D_r3.csv', '2019_07_EnergyPrices_12.1.D_r3.csv', '2019_08_EnergyPrices_12.1.D_r3.csv', '2019_09_EnergyPrices_12.1.D_r3.csv', '2019_10_EnergyPrices_12.1.D_r3.csv', '2019_11_EnergyPrices_12.1.D_r3.csv', '2019_12_EnergyPrices_12.1.D_r3.csv', '2020_01_EnergyPrices_12.1.D_r3.csv', '2020_02_EnergyPrices_12.1.D_r3.csv', '2020_03_EnergyPrices_12.1.D_r3.csv', '2020_04_EnergyPrices_12.1.D_r3.csv', '2020_05_EnergyPrices_12.1.D_r3.csv', '2020_06_EnergyPrices_12.1.D_r3.csv', '2020_07_EnergyPrices_12.1.D_r3.csv', '2020_08_EnergyPrices_12.1.D_r3.csv', '2020_09_EnergyPrices_12.1.D_r3.csv', '2020_10_EnergyPrices_12.1.D_r3.csv', '2020_11_EnergyPrices_12.1.D_r3.csv', '2020_12_EnergyPrices_12.1.D_r3.csv', '2021_01_EnergyPrices_12.1.D_r3.csv', '2021_02_EnergyPrices_12.1.D_r3.csv', '2021_03_EnergyPrices_12.1.D_r3.csv', '2021_04_EnergyPrices_12.1.D_r3.csv', '2021_05_EnergyPrices_12.1.D_r3.csv', '2021_06_EnergyPrices_12.1.D_r3.csv', '2021_07_EnergyPrices_12.1.D_r3.csv', '2021_08_EnergyPrices_12.1.D_r3.csv', '2021_09_EnergyPrices_12.1.D_r3.csv', '2021_10_EnergyPrices_12.1.D_r3.csv', '2021_11_EnergyPrices_12.1.D_r3.csv', '2021_12_EnergyPrices_12.1.D_r3.csv', '2022_01_EnergyPrices_12.1.D_r3.csv', '2022_02_EnergyPrices_12.1.D_r3.csv', '2022_03_EnergyPrices_12.1.D_r3.csv', '2022_04_EnergyPrices_12.1.D_r3.csv', '2022_05_EnergyPrices_12.1.D_r3.csv', '2022_06_EnergyPrices_12.1.D_r3.csv', '2022_07_EnergyPrices_12.1.D_r3.csv', '2022_08_EnergyPrices_12.1.D_r3.csv', '2022_09_EnergyPrices_12.1.D_r3.csv', '2022_10_EnergyPrices_12.1.D_r3.csv', '2022_11_EnergyPrices_12.1.D_r3.csv', '2022_12_EnergyPrices_12.1.D_r3.csv', '2023_01_EnergyPrices_12.1.D_r3.csv', '2023_02_EnergyPrices_12.1.D_r3.csv', '2023_03_EnergyPrices_12.1.D_r3.csv', '2023_04_EnergyPrices_12.1.D_r3.csv', '2023_05_EnergyPrices_12.1.D_r3.csv', '2023_06_EnergyPrices_12.1.D_r3.csv', '2023_07_EnergyPrices_12.1.D_r3.csv', '2023_08_EnergyPrices_12.1.D_r3.csv', '2023_09_EnergyPrices_12.1.D_r3.csv', '2023_10_EnergyPrices_12.1.D_r3.csv', '2023_11_EnergyPrices_12.1.D_r3.csv', '2023_12_EnergyPrices_12.1.D_r3.csv', '2024_01_EnergyPrices_12.1.D_r3.csv', '2024_02_EnergyPrices_12.1.D_r3.csv', '2024_03_EnergyPrices_12.1.D_r3.csv', '2024_04_EnergyPrices_12.1.D_r3.csv', '2024_05_EnergyPrices_12.1.D_r3.csv', '2024_06_EnergyPrices_12.1.D_r3.csv', '2024_07_EnergyPrices_12.1.D_r3.csv', '2024_08_EnergyPrices_12.1.D_r3.csv', '2024_09_EnergyPrices_12.1.D_r3.csv', '2024_10_EnergyPrices_12.1.D_r3.csv', '2024_11_EnergyPrices_12.1.D_r3.csv', '2024_12_EnergyPrices_12.1.D_r3.csv', '2025_01_EnergyPrices_12.1.D_r3.csv', '2025_02_EnergyPrices_12.1.D_r3.csv', '2025_03_EnergyPrices_12.1.D_r3.csv', '2025_04_EnergyPrices_12.1.D_r3.csv', '2025_05_EnergyPrices_12.1.D_r3.csv', '2025_06_EnergyPrices_12.1.D_r3.csv', '2025_07_EnergyPrices_12.1.D_r3.csv']

## load data

In [205]:
#set paths and get file names
path_prices = path+'EnergyPrices_12.1.D_r3/'
path_prices_local = path_local+'prices/'

# Leon: (Ordner sicherstellen)
os.makedirs(path_prices_local, exist_ok=True)

if download =="yes":
    with pysftp.Connection(host=host, username=username, password=password) as sftp:
        print("Connection succesfully established.")
        # show list of files
        files = sftp.listdir(path_prices)
if download =="no": 
    files = os.listdir(path_prices_local)
if year != "":
    files = [i for i in files if year in i]
    print(files)   # Leon, um sie anzuzeigen

Connection succesfully established.
['2024_01_EnergyPrices_12.1.D_r3.csv', '2024_02_EnergyPrices_12.1.D_r3.csv', '2024_03_EnergyPrices_12.1.D_r3.csv', '2024_04_EnergyPrices_12.1.D_r3.csv', '2024_05_EnergyPrices_12.1.D_r3.csv', '2024_06_EnergyPrices_12.1.D_r3.csv', '2024_07_EnergyPrices_12.1.D_r3.csv', '2024_08_EnergyPrices_12.1.D_r3.csv', '2024_09_EnergyPrices_12.1.D_r3.csv', '2024_10_EnergyPrices_12.1.D_r3.csv', '2024_11_EnergyPrices_12.1.D_r3.csv', '2024_12_EnergyPrices_12.1.D_r3.csv']

In [206]:
#download aggregated data
if download =="yes":
    with pysftp.Connection(host=host, username=username, password=password) as sftp:
        for file in files:
            sftp.get(path_prices+file,path_prices_local+file)
            print('Successfully downloaded file '+file)

Successfully downloaded file 2024_01_EnergyPrices_12.1.D_r3.csv
Successfully downloaded file 2024_02_EnergyPrices_12.1.D_r3.csv
Successfully downloaded file 2024_03_EnergyPrices_12.1.D_r3.csv
Successfully downloaded file 2024_04_EnergyPrices_12.1.D_r3.csv
Successfully downloaded file 2024_05_EnergyPrices_12.1.D_r3.csv
Successfully downloaded file 2024_06_EnergyPrices_12.1.D_r3.csv
Successfully downloaded file 2024_07_EnergyPrices_12.1.D_r3.csv
Successfully downloaded file 2024_08_EnergyPrices_12.1.D_r3.csv
Successfully downloaded file 2024_09_EnergyPrices_12.1.D_r3.csv
Successfully downloaded file 2024_10_EnergyPrices_12.1.D_r3.csv
Successfully downloaded file 2024_11_EnergyPrices_12.1.D_r3.csv
Successfully downloaded file 2024_12_EnergyPrices_12.1.D_r3.csv

In [207]:
#Leon
import chardet
# Eine der Datein testen
test_file = path_prices_local + files[0]
print("Prüfe Datei:", test_file)

# Encoding automatisch erkennen
with open(test_file, 'rb') as f:
    result = chardet.detect(f.read(50000)) # nur ersten Teil lesen
print("Erkanntes Encoding:", result)

# Datei mit erkanntem Encoding laden
df_test = pd.read_csv(test_file, sep="\t", encoding=result['encoding'], nrows=5)
print("Spalten:", df_test.columns.tolist())

Prüfe Datei: ..\source_data/ENTSOE/prices/2024_01_EnergyPrices_12.1.D_r3.csv
Erkanntes Encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
Spalten: ['InstanceCode', 'DateTime(UTC)', 'ResolutionCode', 'AreaCode', 'AreaDisplayName', 'AreaTypeCode', 'MapCode', 'ContractType', 'Sequence', 'Price[Currency/MWh]', 'Currency', 'UpdateTime(UTC)']

In [208]:
#combine files to one data frame
df_prices = pd.DataFrame()
for file in files:
    df_temp = pd.read_csv(path_prices_local+file,
                          decimal=".",encoding="UTF-8-SIG",sep="\t",      # leon, updated encoding
                          parse_dates=True, index_col="DateTime(UTC)")    # Leon, neue Bezeichnungen
    
    #df_prices = df_prices.append(df_temp)
    df_prices = pd.concat([df_prices, df_temp], ignore_index=False) # Leon, in pandas 2.0 gibt es .append() nicht mehr als Methode
    
df_prices = df_prices.drop(['ResolutionCode','AreaCode','AreaTypeCode','AreaDisplayName','UpdateTime(UTC)'], axis=1) # Leon, AreaName ersetzt durch AreaDisplayName 
df_prices.head()

,InstanceCode,MapCode,ContractType,Sequence,Price[Currency/MWh],Currency
DateTime(UTC),,,,,,
2024-01-01 00:00:00,79b1a5b9cd1ed1b08ff37178ba3cd9dc,AT,Day-ahead,1,0.01,EUR
2024-01-01 01:00:00,79b1a5b9cd1ed1b08ff37178ba3cd9dc,AT,Day-ahead,1,0.02,EUR
2024-01-01 02:00:00,79b1a5b9cd1ed1b08ff37178ba3cd9dc,AT,Day-ahead,1,0.00,EUR
2024-01-01 03:00:00,79b1a5b9cd1ed1b08ff37178ba3cd9dc,AT,Day-ahead,1,-0.01,EUR
2024-01-01 04:00:00,79b1a5b9cd1ed1b08ff37178ba3cd9dc,AT,Day-ahead,1,-0.01,EUR

In [209]:
# Leon: 
# 1. Spalte (Preis) umbenennen (nach dem Einlesen), damit unterer Code beibehalten werden kann
df_prices = df_prices.rename(columns={
'Price[Currency/MWh]': 'Price',
})
df_prices.head()

,InstanceCode,MapCode,ContractType,Sequence,Price,Currency
DateTime(UTC),,,,,,
2024-01-01 00:00:00,79b1a5b9cd1ed1b08ff37178ba3cd9dc,AT,Day-ahead,1,0.01,EUR
2024-01-01 01:00:00,79b1a5b9cd1ed1b08ff37178ba3cd9dc,AT,Day-ahead,1,0.02,EUR
2024-01-01 02:00:00,79b1a5b9cd1ed1b08ff37178ba3cd9dc,AT,Day-ahead,1,0.00,EUR
2024-01-01 03:00:00,79b1a5b9cd1ed1b08ff37178ba3cd9dc,AT,Day-ahead,1,-0.01,EUR
2024-01-01 04:00:00,79b1a5b9cd1ed1b08ff37178ba3cd9dc,AT,Day-ahead,1,-0.01,EUR

Convert to EUR using exchange rates from ECB: (Leon, aktualisiert) 
https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html

- GBP->EUR: 1.1527377521613833  
- RON->EUR: 0.19719976336028397
- PLN->EUR: 0.23500105750475878
- BGN->EUR: 0.5112997238981491

In [210]:
#Convert to EUR using exchange rates from ECB: (Leon, tagesaktuell)

import requests
import xml.etree.ElementTree as ET

# Daten laden
url = "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml"
response = requests.get(url)
root = ET.fromstring(response.content)

# Namensräume der XML beachten
ns = {'gesmes': 'http://www.gesmes.org/xml/2002-08-01',
'def': 'http://www.ecb.int/vocabulary/2002-08-01/eurofxref'}

# Dictionary: 1 EUR = X Currency
rates_eur = {cube.attrib['currency']: float(cube.attrib['rate'])
for cube in root.findall('.//def:Cube/def:Cube/def:Cube', ns)}

# Kehrwert berechnen: 1 Currency = X EUR
exchange = {cur: 1 / rates_eur[cur] for cur in ['GBP', 'PLN', 'RON', 'BGN']}

print(exchange)

{'GBP': 1.1474469305794606, 'PLN': 0.2350562959828879, 'RON': 0.19721143037450448, 'BGN': 0.5112997238981491}

In [211]:
exchange['GBP']

1.1474469305794606

In [212]:
#df_prices.Price[df_prices.Currency == 'GBP'] = df_prices.Price * exchange['GBP']
#df_prices.Price[df_prices.Currency == 'RON'] = df_prices.Price * exchange['RON']
#df_prices.Price[df_prices.Currency == 'PLN'] = df_prices.Price * exchange['PLN']
#df_prices.Price[df_prices.Currency == 'BGN'] = df_prices.Price * exchange['BGN']

# Leon, Alternativ: (ohne Warnmeldung, weil kein Chained Assignment mehr) 
df_prices.loc[df_prices['Currency'] == 'GBP', 'Price'] *= exchange['GBP']
df_prices.loc[df_prices['Currency'] == 'RON', 'Price'] *= exchange['RON']
df_prices.loc[df_prices['Currency'] == 'PLN', 'Price'] *= exchange['PLN']
df_prices.loc[df_prices['Currency'] == 'BGN', 'Price'] *= exchange['BGN']


df_prices = df_prices.drop(columns = 'Currency').reset_index().rename(columns={'DateTime(UTC)':'date'}).set_index(['date','MapCode'])
df_prices.head()

# Leon: vorheriger Code erzeugt FutureWarning - funktioniert aber noch unter der pd - Version (siehe oben)

,,InstanceCode,ContractType,Sequence,Price
date,MapCode,,,,
2024-01-01 00:00:00,AT,79b1a5b9cd1ed1b08ff37178ba3cd9dc,Day-ahead,1,0.01
2024-01-01 01:00:00,AT,79b1a5b9cd1ed1b08ff37178ba3cd9dc,Day-ahead,1,0.02
2024-01-01 02:00:00,AT,79b1a5b9cd1ed1b08ff37178ba3cd9dc,Day-ahead,1,0.00
2024-01-01 03:00:00,AT,79b1a5b9cd1ed1b08ff37178ba3cd9dc,Day-ahead,1,-0.01
2024-01-01 04:00:00,AT,79b1a5b9cd1ed1b08ff37178ba3cd9dc,Day-ahead,1,-0.01

In [213]:
df_prices_pivot = df_prices.reset_index().pivot_table(index='date',columns='MapCode',values='Price')
df_prices_hourly = df_prices_pivot.resample('h').mean()  # Leon, h statt H wegen Warnmeldung 
df_prices_hourly.head()

MapCode,AT,BE,BG,CH,CZ,DE_LU,DK1,DK2,EE,ES,...,PT,RO,RS,SE1,SE2,SE3,SE4,SI,SK,UA_IPS
date,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00,1.54125,0.01,0.01,21.99,0.01,-3.10375,28.14,28.46,28.46,50.09,...,50.09,0.01,5.02,28.46,28.46,28.46,28.46,0.01,0.01,55.55
2024-01-01 01:00:00,0.98125,0.00,0.04,14.32,0.02,-0.13625,26.66,26.66,26.66,47.50,...,47.50,0.04,1.10,26.66,26.66,26.66,26.66,0.03,0.05,38.00
2024-01-01 02:00:00,1.12250,-0.01,0.01,11.37,0.00,-4.05375,4.14,24.48,24.48,43.50,...,43.50,0.01,2.30,24.48,24.48,24.48,24.48,0.00,0.01,32.00
2024-01-01 03:00:00,2.82625,-0.03,0.01,11.35,-0.01,-2.21500,-0.03,24.01,24.01,42.50,...,42.50,0.01,2.27,24.01,24.01,24.01,24.01,0.00,0.01,30.00
2024-01-01 04:00:00,-1.76000,-0.02,0.01,11.39,-0.01,-1.83750,-0.02,15.88,21.23,42.09,...,42.09,0.01,5.40,21.23,21.23,21.23,21.23,0.00,0.01,30.00

In [214]:
df_prices_stack = pd.DataFrame(df_prices_hourly.stack()).rename(columns={0:'EUR_per_MWh'}).reset_index()
df_prices_stack['country'] = df_prices_stack.MapCode.map(map_country)
print(df_prices_stack['MapCode'].unique())

['AT' 'BE' 'BG' 'CH' 'CZ' 'DE_LU' 'DK1' 'DK2' 'EE' 'ES' 'FI' 'FR' 'GR'
 'HR' 'HU' 'IE_SEM' 'IT-CNORTH' 'IT-CSOUTH' 'IT-Calabria' 'IT-NORTH'
 'IT-SACOAC' 'IT-SACODC' 'IT-SOUTH' 'IT-Sardinia' 'IT-Sicily' 'LT' 'LV'
 'ME' 'MK' 'NL' 'NO1' 'NO2' 'NO2NSL' 'NO3' 'NO4' 'NO5' 'PL' 'PT' 'RO' 'RS'
 'SE1' 'SE2' 'SE3' 'SE4' 'SI' 'SK' 'UA_IPS']

In [215]:
### Fehlende Länder ??? (Mapping)

print(df_prices_stack['country'].unique()) # nach dem ersten Mapping

['AT' 'BE' 'BG' 'CH' 'CZ' 'DE' 'DK' 'EE' 'ES' 'FI' 'FR' 'GR' 'HR' 'HU'
 'IE' 'IT' 'LT' 'LV' 'ME' 'MK' 'NL' 'NO' 'PL' 'PT' 'RO' 'RS' 'SE' 'SI'
 'SK' 'UA']

now we also load load values for weighting in countries with multiple bidding zones

In [216]:
#set paths and get file names
path_load = path+'ActualTotalLoad_6.1.A/'  # Leon, aktualisiert
path_load_local = path_local+'load/'

# Leon: (Ordner sicherstellen)
os.makedirs(path_load_local, exist_ok=True)

if download =="yes":
    with pysftp.Connection(host=host, username=username, password=password) as sftp:
        print("Connection succesfully established.")
        # show list of files
        files = sftp.listdir(path_load)
        #print(files)  # Leon 
if download =="no": 
    files = os.listdir(path_load_local)
if year != "":
    files = [i for i in files if year in i]

Connection succesfully established.

In [217]:
#download aggregated load data (ActualTotalLoad)
if download =="yes":
    with pysftp.Connection(host=host, username=username, password=password) as sftp:
        for file in files:
            sftp.get(path_load+file,path_load_local+file)
            print('Successfully downloaded file '+file)

Successfully downloaded file 2024_01_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_02_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_03_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_04_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_05_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_06_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_07_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_08_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_09_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_10_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_11_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_12_ActualTotalLoad_6.1.A.csv

In [218]:
#combine files to one data frame
df_load = pd.DataFrame()
for file in files:
    df_temp = pd.read_csv(path_load_local+file,
                          decimal=".",encoding="UTF-8-SIG",sep="\t",   # Leon, updated encoding
                          parse_dates=True, index_col="DateTime").drop("AreaCode", axis=1)
    #df_load = df_load.append(df_temp)
    df_load = pd.concat([df_load, df_temp], ignore_index=False) # Leon, in pandas 2.0 gibt es .append() nicht mehr als Methode    
df_load = df_load[df_load.AreaTypeCode == "BZN"].drop(["AreaTypeCode",'ResolutionCode','AreaName','UpdateTime'], axis=1).reset_index()
df_load = df_load.rename(columns={'DateTime':'date'})
df_load = df_load
df_load.head()

                 date MapCode  TotalLoadValue
0 2024-01-27 00:00:00      RS         4511.00
1 2024-01-27 00:45:00      NL        11978.97
2 2024-01-27 00:00:00      BA          657.34
3 2024-01-27 00:00:00      GR         4811.00
4 2024-01-27 00:00:00   DE_LU        50573.27

In [219]:
#resample to hourly
df_load_pivot = df_load.pivot_table(index="date",columns="MapCode",values='TotalLoadValue')
df_load_pivot_hourly = df_load_pivot.resample('1h').mean() # h anstatt H wegen Warnmeldung
df_load_hourly = pd.DataFrame(df_load_pivot_hourly.stack()).rename(columns={0:'TotalLoadValue'}).reset_index()
df_load_hourly['country'] = df_load_hourly.MapCode.map(map_country)
df_load_hourly = df_load_hourly[df_load_hourly.country.isin(bz_countries)]
df_load_hourly.head()

         date      MapCode  TotalLoadValue country
9  2024-01-01          DK1         2241.74      DK
10 2024-01-01          DK2         1462.71      DK
20 2024-01-01    IT-CNORTH         1727.00      IT
21 2024-01-01    IT-CSOUTH         4517.00      IT
22 2024-01-01  IT-Calabria          555.00      IT

In [220]:
df_load_country = df_load_hourly.groupby(['date','country']).sum().reset_index()
df_load_country.head()

,date,country,MapCode,TotalLoadValue
0,2024-01-01 00:00:00,DK,DK1DK2,3704.45
1,2024-01-01 00:00:00,IT,IT-CNORTHIT-CSOUTHIT-CalabriaIT-NORTHIT-SOUTHI...,19910.00
2,2024-01-01 00:00:00,NO,NO1NO2NO3NO4NO5,18363.75
3,2024-01-01 00:00:00,SE,SE1SE2SE3SE4,16763.00
4,2024-01-01 01:00:00,DK,DK1DK2,3638.33

In [221]:
df_load_hourly = df_load_hourly.drop(columns='country')

In [222]:
df_prices_temp = df_prices_stack.merge(df_load_hourly,on=['date','MapCode'],how='left')
df_prices_temp_2 = df_prices_temp.merge(df_load_country,on=['date','country'],how='left')
df_prices_temp_2['weight'] = df_prices_temp_2.TotalLoadValue_x / df_prices_temp_2.TotalLoadValue_y
df_prices_temp_2['weight'][~df_prices_temp_2.country.isin(bz_countries)] = df_prices_temp_2['weight'].fillna(1)
df_prices_temp_2['EUR_per_MWh'] = df_prices_temp_2['EUR_per_MWh'] * df_prices_temp_2['weight']
df_prices_temp_2.tail()

C:\Users\UDuer\AppData\Local\Temp\ipykernel_11584\3176826473.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_prices_temp_2['weight'][~df_prices_temp_2.country.isin(bz_countries)] = df_prices_temp_2['weight'].fillna(1)
C:\Users\UDuer\AppData\Local\Temp\ipykernel_11584\3176826473.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_prices_temp_2['weight'][~df_prices_temp_2.country.isin(bz_countries)] = df_prices_temp_2['weight'].fillna(1)

,date,MapCode_x,EUR_per_MWh,country,TotalLoadValue_x,MapCode_y,TotalLoadValue_y,weight
412747,2024-12-31 23:00:00,SE3,2.029456,SE,9848.0,SE1SE2SE3SE4,15334.0,0.642233
412748,2024-12-31 23:00:00,SE4,0.377498,SE,2168.0,SE1SE2SE3SE4,15334.0,0.141385
412749,2024-12-31 23:00:00,SI,118.460000,SI,NaN,NaN,NaN,1.000000
412750,2024-12-31 23:00:00,SK,180.000000,SK,NaN,NaN,NaN,1.000000
412751,2024-12-31 23:00:00,UA_IPS,2900.000000,UA,NaN,NaN,NaN,1.000000

In [223]:
df_prices_hourly_stack = df_prices_temp_2.groupby(['date','country']).sum().reset_index()
df_prices_hourly_stack.head()

,date,country,MapCode_x,EUR_per_MWh,TotalLoadValue_x,MapCode_y,TotalLoadValue_y,weight
0,2024-01-01,AT,AT,1.54125,0.0,0,0.0,1.0
1,2024-01-01,BE,BE,0.01000,0.0,0,0.0,1.0
2,2024-01-01,BG,BG,0.01000,0.0,0,0.0,1.0
3,2024-01-01,CH,CH,21.99000,0.0,0,0.0,1.0
4,2024-01-01,CZ,CZ,0.01000,0.0,0,0.0,1.0

In [224]:
df_prices_hourly = df_prices_hourly_stack[['date','country','EUR_per_MWh']].pivot_table(index='date',columns='country',values='EUR_per_MWh')
df_prices_hourly.head()

country,AT,BE,BG,CH,CZ,DE,DK,EE,ES,FI,...,NL,NO,PL,PT,RO,RS,SE,SI,SK,UA
date,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00,1.54125,0.01,0.01,21.99,0.01,-3.10375,28.266353,28.46,50.09,28.46,...,0.01,42.347332,74.50,50.09,0.01,5.02,28.46,0.01,0.01,55.55
2024-01-01 01:00:00,0.98125,0.00,0.04,14.32,0.02,-0.13625,26.660000,26.66,47.50,26.66,...,0.00,30.046090,73.29,47.50,0.04,1.10,26.66,0.03,0.05,38.00
2024-01-01 02:00:00,1.12250,-0.01,0.01,11.37,0.00,-4.05375,11.857097,24.48,43.50,24.48,...,-0.01,27.549256,71.58,43.50,0.01,2.30,24.48,0.00,0.01,32.00
2024-01-01 03:00:00,2.82625,-0.03,0.01,11.35,-0.01,-2.21500,9.083792,24.01,42.50,24.01,...,-0.03,27.037858,73.27,42.50,0.01,2.27,24.01,0.00,0.01,30.00
2024-01-01 04:00:00,-1.76000,-0.02,0.01,11.39,-0.01,-1.83750,5.986804,21.23,42.09,21.23,...,-0.02,25.018943,74.32,42.09,0.01,5.40,21.23,0.00,0.01,30.00

In [225]:
#Leon: Fehlende Länder (Mapping)
print(df_prices_hourly.columns.tolist())
# wieso ist DE und LU gar nicht mehr drin ?

['AT', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'UA']

In [230]:
df_prices_hourly['AT']

date
2024-01-01 00:00:00      1.54125
2024-01-01 01:00:00      0.98125
2024-01-01 02:00:00      1.12250
2024-01-01 03:00:00      2.82625
2024-01-01 04:00:00     -1.76000
                         ...
2024-12-31 19:00:00    104.10250
2024-12-31 20:00:00    104.13750
2024-12-31 21:00:00     95.82000
2024-12-31 22:00:00     84.20500
2024-12-31 23:00:00     90.52125
Name: AT, Length: 8784, dtype: float64

In [231]:
df_prices_hourly['LU']=df_prices_hourly['DE']

In [ ]:
df_prices_hourly.to_csv(dir_out+'prices_'+year+'_hourly_entsoe.csv', encoding="utf-8")